name: Build and deploy JAR app to Azure Web App - student-nema

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests
        working-directory: ./student

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ./student/target/*.jar   # <-- ye relative path correct hai

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: deploy-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2A0C858875FF48FC99B3C1424A7B499C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D509415683BA41088CA7348EF7B03356 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_087D1CE7D1B542E8A9234B7778981513 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: student-nema
          slot-name: Production
          package: deploy-artifact/*.jar   # <-- ye wahi folder jaha artifact download hua
